---
# This playbook deploys the LAMP application stack in this site.

- name: deploy and configure the webservers and application
  hosts: all
  remote_user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: all
  remote_user: root

  roles:
    - db
